fixtures:
  symlinks:
    "dlrn": "#{source_dir}"
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    selinux:
      repo: git://github.com/voxpupuli/puppet-selinux.git
    ssh:
      repo: git://github.com/saz/puppet-ssh.git
      ref: "v4.0.0"
    sudo: git://github.com/saz/puppet-sudo.git
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
    lvm: git://github.com/puppetlabs/puppetlabs-lvm.git
    yum: git://github.com/CERIT-SC/puppet-yum.git
    firewalld: git://github.com/crayfishx/puppet-firewalld.git
    wget: git://github.com/maestrodev/puppet-wget.git
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    letsencrypt:
      repo: git://github.com/voxpupuli/puppet-letsencrypt.git
      ref: "af7a12862d0b77211ba91ea1b5455adc254fcd48"
    inifile: git://github.com/puppetlabs/puppetlabs-inifile.git
    rsync: git://github.com/puppetlabs/puppetlabs-rsync.git
    xinetd: git://github.com/puppetlabs/puppetlabs-xinetd.git
