---
- job:
    name: dlrn-puppet-lint
    run: playbooks/puppet/lint.yaml
    nodeset:
      nodes:
        - name: centos-7
          label: rdo-centos-7-vexxhost

- job:
    name: dlrn-puppet-spec
    run: playbooks/puppet/spec.yaml
    nodeset:
      nodes:
        - name: centos-7
          label: rdo-centos-7-vexxhost

- job:
    name: dlrn-puppet-syntax
    run: playbooks/puppet/syntax.yaml
    nodeset:
      nodes:
        - name: centos-7
          label: rdo-centos-7-vexxhost
